[build]
  base = "."
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/static/index.html"
  status = 200