[build]
  base = "."
  publish = "public"
  command = "npm run build"  # Adjust command based on your static site generator

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run start"  # Adjust command based on your static site generator
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200